// Repo-specific pre-build for design-sync.
//
// Beebop's "design system" is an app surface (Next.js + Tailwind), not a
// published component library, so the standard converter needs two things
// staged first — both regenerated into frontend/.ds-cache/ (gitignored):
//
//   1. entry.tsx  — a narrow barrel re-exporting ONLY the scoped components
//                   (cfg.componentSrcMap), so esbuild bundles those instead of
//                   the whole app (synth-entry would pull in next/font, stores,
//                   server code and fail).
//   2. bundle.css — the app's Tailwind theme compiled to a real stylesheet
//                   (cfg.cssEntry → becomes _ds_bundle.css), with the brand-font
//                   prelude prepended (css-prelude.css).
//
// Run this BEFORE package-build.mjs / resync.mjs on every sync:
//   node .design-sync/prepare.mjs
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)); // .design-sync/
const repo = resolve(here, '..');
const frontend = join(repo, 'frontend');
const cacheDir = join(frontend, '.ds-cache');
mkdirSync(cacheDir, { recursive: true });

// 1. Entry barrel from cfg.componentSrcMap (grouped by source file).
const cfg = JSON.parse(readFileSync(join(here, 'config.json'), 'utf8'));
const byFile = new Map();
for (const [name, rel] of Object.entries(cfg.componentSrcMap ?? {})) {
  if (!rel) continue; // null = excluded
  const spec = '../' + rel.replace(/\.(tsx|ts|jsx|js)$/, '');
  (byFile.get(spec) ?? byFile.set(spec, []).get(spec)).push(name);
}
const entry =
  '// GENERATED by .design-sync/prepare.mjs — do not edit (regenerated each sync).\n' +
  [...byFile].map(([spec, names]) => `export { ${names.join(', ')} } from ${JSON.stringify(spec)};`).join('\n') +
  '\n';
writeFileSync(join(cacheDir, 'entry.tsx'), entry);
console.error(`entry.tsx: ${Object.values(cfg.componentSrcMap ?? {}).filter(Boolean).length} component(s) from ${byFile.size} file(s)`);

// 2. Compile the app's Tailwind theme to a real stylesheet (cwd = frontend so
//    the config's content globs resolve frontend-relative).
const twCli = join(frontend, 'node_modules', 'tailwindcss', 'lib', 'cli.js');
if (!existsSync(twCli)) {
  console.error(`! tailwind CLI not found at ${twCli} — run \`npm ci\` in frontend/`);
  process.exit(1);
}
const twOut = join(cacheDir, '_tw.css');
execFileSync(process.execPath, [
  twCli,
  '-c', join(here, 'tailwind.config.ds.ts'),
  '-i', join(frontend, 'src', 'styles', 'globals.css'),
  '-o', twOut,
  '--minify',
], { cwd: frontend, stdio: 'inherit' });

// 3. Prepend the brand-font prelude → bundle.css (cfg.cssEntry).
const prelude = readFileSync(join(here, 'css-prelude.css'), 'utf8').trimEnd();
const tw = readFileSync(twOut, 'utf8');
writeFileSync(join(cacheDir, 'bundle.css'), prelude + '\n\n' + tw);
console.error(`bundle.css: ${(tw.length / 1024).toFixed(0)} KB Tailwind + font prelude → frontend/.ds-cache/bundle.css`);
