"""Agreement PDF rendering.

Uses ReportLab — no system dependencies, works on Render free tier without
extra build packages. The actual legal templates must be signed off by the
property lawyer (dev plan §8.5 prerequisite); this module renders structured
data into the agreed shape.
"""

from __future__ import annotations

import io
from datetime import datetime

from app.models._enums import AgreementType


def render_agreement_pdf(
    *, agreement_type: AgreementType, data: dict
) -> bytes:
    """Return a PDF byte string for the given agreement.

    `data` is the `Agreement.rendered_data` JSONB — fully pre-filled at
    generation time so re-rendering after a signature is deterministic.
    """

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
    from reportlab.lib import colors

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title="Beebop Agreement",
    )
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=16, leading=20)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, leading=16)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, leading=10, textColor=colors.grey)

    title = "Tenancy Agreement" if agreement_type == AgreementType.TENANCY else "Sale Memorandum"

    story: list = [
        Paragraph(title, h1),
        Spacer(1, 6),
        Paragraph(
            f"Generated by Beebop on {datetime.utcnow().strftime('%d %B %Y')} — agreement reference {data.get('reference', '—')}.",
            small,
        ),
        Spacer(1, 12),
    ]

    parties = data.get("parties", {})
    landlord = parties.get("landlord", {})
    seeker = parties.get("seeker", {})
    party_table = Table(
        [
            [
                Paragraph(
                    f"<b>{'LANDLORD' if agreement_type == AgreementType.TENANCY else 'SELLER'}</b><br/>{landlord.get('name', '—')}<br/>{landlord.get('email', '—')}",
                    body,
                ),
                Paragraph(
                    f"<b>{'TENANT' if agreement_type == AgreementType.TENANCY else 'BUYER'}</b><br/>{seeker.get('name', '—')}<br/>{seeker.get('email', '—')}",
                    body,
                ),
            ],
        ],
        colWidths=[doc.width / 2.0, doc.width / 2.0],
    )
    party_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )
    story.extend([party_table, Spacer(1, 14)])

    story.append(Paragraph("Property", h2))
    listing = data.get("listing", {})
    story.append(
        Paragraph(
            f"<b>{listing.get('title', '—')}</b><br/>"
            f"{listing.get('address_line', '—')}<br/>"
            f"District: {listing.get('district', '—')}",
            body,
        )
    )
    story.append(Spacer(1, 12))

    story.append(Paragraph("Commercial terms", h2))
    if agreement_type == AgreementType.TENANCY:
        terms_rows = [
            ["Annual rent", f"₦{int(data.get('price', 0)):,}"],
            ["Term start", str(data.get("start_date", "—"))],
            ["Term end", str(data.get("end_date", "—"))],
        ]
    else:
        terms_rows = [
            ["Sale price", f"₦{int(data.get('price', 0)):,}"],
            ["Effective date", str(data.get("start_date", "—"))],
        ]
    terms_table = Table(terms_rows, colWidths=[doc.width * 0.4, doc.width * 0.6])
    terms_table.setStyle(
        TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.extend([terms_table, Spacer(1, 14)])

    if data.get("conditions"):
        story.append(Paragraph("Additional conditions", h2))
        story.append(Paragraph(str(data["conditions"]).replace("\n", "<br/>"), body))
        story.append(Spacer(1, 14))

    story.append(Paragraph("Beebop facilitation", h2))
    story.append(
        Paragraph(
            "Beebop facilitates this transaction. The platform's trust badges, "
            "verification process, and dispute-resolution channels apply. "
            "All payments and renewals are managed through the Beebop dashboard.",
            body,
        )
    )
    story.append(Spacer(1, 18))

    story.append(Paragraph("Signatures", h2))
    sigs = data.get("signatures", [])
    sig_lines = []
    for s in sigs:
        sig_lines.append(
            f"• {s.get('party', '?').title()}: signed via {s.get('channel', '?')} at {s.get('signed_at', '—')}"
        )
    if not sig_lines:
        sig_lines = ["• Awaiting both parties' OTP-confirmed signatures."]
    for line in sig_lines:
        story.append(Paragraph(line, body))

    doc.build(story)
    return buffer.getvalue()
