"""Search request / response schemas."""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field

from app.models._enums import Gender, ListingCategory, ListingStatus

VerificationTier = Literal["fully_verified", "doc_verified", "unverified"]

SortOption = Literal[
    "relevance",
    "price_asc",
    "price_desc",
    "newest",
    "highest_rated",
]


class SharedFilters(BaseModel):
    """Every category shares these."""

    q: str | None = None
    locations: list[str] = Field(default_factory=list)
    verification: list[VerificationTier] = Field(
        default_factory=lambda: ["fully_verified", "doc_verified", "unverified"]
    )
    amenities: list[str] = Field(default_factory=list)  # format: "group:key"
    min_price: float | None = Field(default=None, ge=0)
    max_price: float | None = Field(default=None, ge=0)
    sort: SortOption = "relevance"
    page: int = Field(default=1, ge=1)
    page_size: int = Field(default=24, ge=1, le=60)


class OffCampusFilters(SharedFilters):
    use_profile_filters: bool = False
    institution: str | None = None
    gender: Gender | None = None
    unit_kinds: list[str] = Field(default_factory=list)
    available_now: bool = False


class ShortLetFilters(SharedFilters):
    check_in: date | None = None
    check_out: date | None = None
    guests: int | None = Field(default=None, ge=1)
    min_stay: int | None = Field(default=None, ge=1)
    instant_booking: bool | None = None
    min_rating: float | None = Field(default=None, ge=0, le=5)


class RentFilters(SharedFilters):
    bedroom_counts: list[int] = Field(default_factory=list)
    property_types: list[str] = Field(default_factory=list)
    furnishing: list[str] = Field(default_factory=list)
    payment_structure: list[str] = Field(default_factory=list)
    available_from: date | None = None


class SalesFilters(SharedFilters):
    bedroom_counts: list[int] = Field(default_factory=list)
    property_types: list[str] = Field(default_factory=list)
    development_status: list[str] = Field(default_factory=list)
    title_types: list[str] = Field(default_factory=list)


class PublicListingSummary(BaseModel):
    """Shape used on browse grids and map pins."""

    id: str
    category: ListingCategory
    status: ListingStatus
    title: str
    subtitle: str | None = None
    price: float | None = None
    district: str | None = None
    gps_lat: float | None = None
    gps_lng: float | None = None
    cover_url: str | None = None
    rating: float | None = None
    review_count: int = 0


class SearchResponse(BaseModel):
    category: ListingCategory
    total: int
    page: int
    page_size: int
    results: list[PublicListingSummary]


class PublicListingDetail(BaseModel):
    id: str
    category: ListingCategory
    status: ListingStatus
    title: str
    subtitle: str | None = None
    description: str
    district: str | None = None
    gps_lat: float | None = None
    gps_lng: float | None = None
    price: float | None = None
    amenities: dict
    type_data: dict
    photos: list[dict]
    area_score: "PublicAreaScore | None" = None
    # Valuation report lives in a separate object, gated at the API level
    # below. Clients that do not send a bearer token get `valuation_report=None`.
    valuation_report: "ValuationReport | None" = None
    is_bookmarked: bool = False
    rating: float | None = None
    review_count: int = 0


class PublicAreaScore(BaseModel):
    scores: dict | None = None
    last_assessed_at: str | None = None


class ValuationReport(BaseModel):
    """Gated panel shown on the listing page to signed-in users.

    Per v2.0 change: NO fair-market-value indicator and NO comparable listings.
    Only: area infrastructure scores, inspector professional note, report date.
    Generated by Claude at physical-badge issuance (Sprint 7); this Sprint 3
    schema is the consumer shape.
    """

    area_scores: dict | None = None
    area_scores_last_updated: str | None = None
    inspector_note: str | None = None
    report_date: str | None = None   # ISO-8601
