"""initial_schema

Revision ID: f2272edda78c
Revises: 
Create Date: 2026-05-03 09:27:04.836846

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f2272edda78c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_scores',
    sa.Column('cell_lat', sa.Float(), nullable=False),
    sa.Column('cell_lng', sa.Float(), nullable=False),
    sa.Column('road_condition', sa.Integer(), nullable=True),
    sa.Column('electricity_supply_hours', sa.Integer(), nullable=True),
    sa.Column('electricity_supply_hours_reported', sa.Integer(), nullable=True),
    sa.Column('security', sa.Integer(), nullable=True),
    sa.Column('proximity', sa.Integer(), nullable=True),
    sa.Column('landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_scores_cell_lat'), 'area_scores', ['cell_lat'], unique=False)
    op.create_index(op.f('ix_area_scores_cell_lng'), 'area_scores', ['cell_lng'], unique=False)
    op.create_table('listing_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SEEKER', 'LANDLORD', 'AGENT', 'INSPECTOR', 'TRUSTED_AGENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('account_type', sa.Enum('INDIVIDUAL', 'AGENCY', name='account_type'), nullable=True),
    sa.Column('nin', sa.String(length=11), nullable=True),
    sa.Column('nin_verified', sa.Boolean(), nullable=False),
    sa.Column('bvn_verified', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('cac_number', sa.String(length=32), nullable=True),
    sa.Column('cac_verified', sa.Boolean(), nullable=False),
    sa.Column('agency_logo_url', sa.String(length=500), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('operating_area', sa.String(length=255), nullable=True),
    sa.Column('category_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('academic_level', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'ANY', name='gender'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('conduct_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_audit_log',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_entity_id'), 'admin_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_entity_type'), 'admin_audit_log', ['entity_type'], unique=False)
    op.create_table('listings',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('OFF_CAMPUS', 'SHORT_LET', 'RENT', 'SALES', name='listing_category'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_DOC_REVIEW', 'LIVE_UNVERIFIED', 'DOC_VERIFIED', 'FULLY_VERIFIED', 'LET_AGREED', 'SALE_AGREED', 'SUSPENDED', 'DELISTED', name='listing_status'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('type_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('enquiry_count', sa.Integer(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category'), 'listings', ['category'], unique=False)
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'IN_APP', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('badges',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DOCUMENT', 'PHYSICAL', name='badge_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='badge_status'), nullable=False),
    sa.Column('issued_by_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_listing_id'), 'badges', ['listing_id'], unique=False)
    op.create_table('bookings',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('seeker_id', sa.UUID(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status'), nullable=False),
    sa.Column('instant_booking', sa.Boolean(), nullable=False),
    sa.Column('base_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weekend_uplift', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seeker_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('host_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paystack_reference', sa.String(length=200), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('access_details', sa.Text(), nullable=True),
    sa.Column('access_details_released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payout_reference', sa.String(length=200), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_listing_id'), 'bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_bookings_seeker_id'), 'bookings', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_bookmark_user_listing')
    )
    op.create_index(op.f('ix_bookmarks_listing_id'), 'bookmarks', ['listing_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('inspection_reports',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'PENDING', 'APPROVED', 'QUERIED', 'REJECTED', name='inspection_report_status'), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visit_gps_lat', sa.Float(), nullable=True),
    sa.Column('visit_gps_lng', sa.Float(), nullable=True),
    sa.Column('inspector_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_reports_inspector_id'), 'inspection_reports', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_listing_id'), 'inspection_reports', ['listing_id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_status'), 'inspection_reports', ['status'], unique=False)
    op.create_table('listing_documents',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_documents_listing_id'), 'listing_documents', ['listing_id'], unique=False)
    op.create_table('listing_photos',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('room_label', sa.String(length=100), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_inspector_walkthrough', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_photos_listing_id'), 'listing_photos', ['listing_id'], unique=False)
    op.create_table('offers',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('seeker_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'EXPIRED', 'WITHDRAWN', name='offer_status'), nullable=False),
    sa.Column('parent_offer_id', sa.UUID(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('awaiting_landlord_response', sa.Boolean(), nullable=False),
    sa.Column('requires_visit_before_acceptance', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_notifications_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_expires_at'), 'offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    op.create_index(op.f('ix_offers_seeker_id'), 'offers', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('unit_types',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('SINGLE_ROOM', 'TWO_IN_A_ROOM', 'THREE_IN_A_ROOM', 'SELF_CONTAIN', 'CUSTOM', name='unit_kind'), nullable=False),
    sa.Column('beds_per_room', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_types_listing_id'), 'unit_types', ['listing_id'], unique=False)
    op.create_table('agreements',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TENANCY', 'SALE', name='agreement_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PARTIAL_SIGNED', 'PENDING_PAYMENT', 'SIGNED', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='agreement_status'), nullable=False),
    sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_s3_key', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rendered_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sales_invoice_reference', sa.String(length=200), nullable=True),
    sa.Column('sales_invoice_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('landlord_fee_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('seeker_fee_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('seller_fee_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('facilitation_fee_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('landlord_payment_reference', sa.String(length=200), nullable=True),
    sa.Column('seeker_payment_reference', sa.String(length=200), nullable=True),
    sa.Column('paystack_reference', sa.String(length=200), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewed_into_id', sa.UUID(), nullable=True),
    sa.Column('renewal_prompted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['renewed_into_id'], ['agreements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_listing_id'), 'agreements', ['listing_id'], unique=False)
    op.create_index(op.f('ix_agreements_offer_id'), 'agreements', ['offer_id'], unique=False)
    op.create_index(op.f('ix_agreements_status'), 'agreements', ['status'], unique=False)
    op.create_table('chat_threads',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_booking_id'), 'chat_threads', ['booking_id'], unique=True)
    op.create_table('rooms',
    sa.Column('unit_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender_tag', sa.Enum('FEMALE', 'MALE', 'ANY', name='gender'), nullable=False),
    sa.Column('beds_total', sa.Integer(), nullable=False),
    sa.Column('beds_available', sa.Integer(), nullable=False),
    sa.Column('bed_status_summary', sa.Enum('OCCUPIED', 'AVAILABLE', 'VACATING', name='bed_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('beds_available >= 0 AND beds_available <= beds_total', name='ck_room_beds_available_range'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_unit_type_id'), 'rooms', ['unit_type_id'], unique=False)
    op.create_table('visits',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('seeker_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ASSIGNMENT', 'AGENT_ASSIGNED', 'SCHEDULED', 'REPORT_PENDING', 'COMPLETED', 'CANCELLED', 'REPORT_QUERIED', name='visit_status'), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('agent_confirmation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visit_report_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_report_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_report_reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('visit_report_review_note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Enum('SEEKER', 'LANDLORD', 'AGENT', 'ADMIN', name='visit_cancelled_by'), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_report_reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_listing_id'), 'visits', ['listing_id'], unique=False)
    op.create_index(op.f('ix_visits_seeker_id'), 'visits', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_shortcut', sa.String(length=64), nullable=True),
    sa.Column('is_moderator_message', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_flagged'), 'chat_messages', ['flagged'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('reviews',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('rating_accuracy', sa.Integer(), nullable=True),
    sa.Column('rating_cleanliness', sa.Integer(), nullable=True),
    sa.Column('rating_location', sa.Integer(), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_rating BETWEEN 1 AND 5', name='ck_review_overall_range'),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_listing_id'), 'reviews', ['listing_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_listing_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_flagged'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_seeker_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_listing_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_rooms_unit_type_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_chat_threads_booking_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_agreements_status'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_offer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_listing_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_unit_types_listing_id'), table_name='unit_types')
    op.drop_table('unit_types')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_seeker_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_expires_at'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_listing_photos_listing_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    op.drop_index(op.f('ix_listing_documents_listing_id'), table_name='listing_documents')
    op.drop_table('listing_documents')
    op.drop_index(op.f('ix_inspection_reports_status'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_listing_id'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_inspector_id'), table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_listing_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_seeker_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_listing_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_badges_listing_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_category'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_admin_audit_log_entity_type'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_entity_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('listing_amenities')
    op.drop_index(op.f('ix_area_scores_cell_lng'), table_name='area_scores')
    op.drop_index(op.f('ix_area_scores_cell_lat'), table_name='area_scores')
    op.drop_table('area_scores')
    # ### end Alembic commands ###
